site_name: Dev Shards

site_url: https://stawo.github.io/

theme:
  name: material

plugins:
  - search
  - blogging:
      dirs:
        - articles

markdown_extensions:
  - pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg