site_name: Dev Shards

site_url: https://stawo.github.io/

theme:
  name: material
  palette:
    scheme: slate
    accent: amber
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

plugins:
  - search
  - blogging:
      dirs:
        - articles
      features:
        tags: {}
      theme:
        name: card

markdown_extensions:
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg