name: Publish site via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install libraries
      - run: pip install \
          mkdocs-material \
          mkdocs-blogging-plugin
      
      - name: Generate docs
      - run: mkdocs gh-deploy --force
